import type { Metadata } from "next";
import { fedro, ppNeueMontreal } from "./fonts"; 
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        ppNeueMontreal.variable,
        fedro.variable,
        "font-sans"
      )}    >
      <body className="font-sans antialiased min-h-full flex flex-col">
        <a
          href="#main-content"
          className="fixed start-4 top-4 z-50 -translate-y-24 rounded-md bg-background px-4 py-3 font-medium shadow-md transition-transform focus-visible:translate-y-0 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          Skip to Main Content
        </a>
        {children}</body>
    </html>
  );
}
