export type BillingErrorCode =
  | "INVALID_TOTAL_SEN"
  | "NO_PARTICIPANTS"
  | "INVALID_PARTICIPANT_ID"
  | "DUPLICATE_PARTICIPANT_ID"
  | "INVALID_WEIGHT"
  | "INVALID_ALLOCATION_AMOUNT"
  | "OVER_ALLOCATED_ITEM"
  | "INVALID_ITEM_ID"
  | "DUPLICATE_ITEM_ID"
  | "INVALID_ITEM_TOTAL"
  | "INVALID_ADJUSTMENT_ID"
  | "DUPLICATE_ADJUSTMENT_ID"
  | "INVALID_ADJUSTMENT_AMOUNT"
  | "NEGATIVE_CALCULATED_TOTAL"
  | "UNSAFE_CALCULATION"
  | "INVALID_ADJUSTMENT_ALLOCATION_AMOUNT"
  | "ADJUSTMENT_ALLOCATION_SIGN_MISMATCH"
  | "OVER_ALLOCATED_ADJUSTMENT"
  | "UNKNOWN_PARTICIPANT_ID"
  | "DUPLICATE_ITEM_ALLOCATION"
  | "DUPLICATE_ADJUSTMENT_ALLOCATION"
  | "INVALID_QUANTITY"
  | "INVALID_UNIT_PRICE"
  | "INVALID_LINE_TOTAL_OVERRIDE"
  | "INVALID_PERCENTAGE"
  | "PERCENTAGE_EXCEEDS_TOTAL"
  | "QUANTITY_EXCEEDS_TOTAL"
  | "INVALID_PROPORTIONAL_BASE"
  | "NO_PROPORTIONAL_BASE"
  | "INVALID_RATE"
  | "INVALID_ADJUSTMENT_BASE"
  | "INVALID_ADJUSTMENT_OVERRIDE"
  | "ADJUSTMENT_OVERRIDE_SIGN_MISMATCH";

export class BillingDomainError extends Error {
  constructor(
    public readonly code: BillingErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "BillingDomainError";
  }
}